JSON_SAMPLE_MOCK = {
   "availability_slots":[
     {
        "time":"08:00:00",
        "slot_size":10,
        "doctor_id":1
     },
     {
        "time":"08:00:00",
        "slot_size":10,
        "doctor_id":2
     },
     {
        "time":"08:50:00",
        "slot_size":10,
        "doctor_id":2
     },
     {
        "time":"09:10:00",
        "slot_size":10,
        "doctor_id":1
     },
     {
        "time":"09:20:00",
        "slot_size":10,
        "doctor_id":1
     },
     {
        "time":"09:40:00",
        "slot_size":10,
        "doctor_id":1
     },
     {
        "time":"10:50:00",
        "slot_size":10,
        "doctor_id":1
     },
      {
         "time":"13:10:00",
         "slot_size":10,
         "doctor_id":1
      },
      {
         "time":"14:50:00",
         "slot_size":10,
         "doctor_id":1
      },
      {
         "time":"14:50:00",
         "slot_size":10,
         "doctor_id":2
      }
   ]
 }
